env:
  commonjs: true
  es6: true
  jest: true
  node: true

ignorePatterns:
  - "!.*"
  - "**.test.ts"
  - "**.spec.ts"
  - "**/node_modules/.*"
  - "**/dist/.*"
  - "**/coverage/.*"

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: 2023
  sourceType: module
  requireConfigFile: false
  projet: "./tsconfig.json"

plugins:
  - "@typescript-eslint"
  - jest
  - prettier

extends:
  - eslint:recommended
  # -plugin:@typescript-eslint/recommended
  - plugin:github/recommended
  - plugin:jest/recommended

rules:
  camelcase: "off"
